version: '2'
services:
  web:
    container_name: studcee-tut-web
    restart: always
    build: ./web
    expose:
      - "80"
    depends_on:
      - db
    volumes:
      - ./web:/usr/src/app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && pip install pyyaml && python manage.py collectstatic --no-input && python manage.py loaddata languages.yaml && python manage.py loaddata subjects.yaml &&  gunicorn tutoring.wsgi -b 0.0.0.0:80"

  nginx:
    container_name: studcee-tut-nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /static
    volumes_from:
      - web
    depends_on:
      - web

  db:
    container_name: studcee-tut-db
    restart: always
    image: postgres:latest
    # ports:
    #   - "5432:5432"
    # volumes:
    #   - pgdata:/var/lib/postgresql/data/
